import sys                                                                                                                                                                                                                                    
from PyQt6.QtWidgets import QApplication, QWidget, QListWidget, QVBoxLayout, QListWidgetItem                                                                                                                                                  
                                                                                                                                                                                                                                              
class MainWindow(QWidget):                                                                                                                                                                                                                    
    def __init__(self):                                                                                                                                                                                                                       
        super().__init__()                                                                                                                                                                                                                    
                                                                                                                                                                                                                                              
        # Création de la QListWidget                                                                                                                                                                                                          
        self.list_widget = QListWidget()                                                                                                                                                                                                      
                                                                                                                                                                                                                                              
        # Ajout d'éléments à la QListWidget                                                                                                                                                                                                   
        item1 = QListWidgetItem("Element 1")                                                                                                                                                                                                  
        item2 = QListWidgetItem("Element 2")                                                                                                                                                                                                  
        item3 = QListWidgetItem("Element 3")                                                                                                                                                                                                  
                                                                                                                                                                                                                                              
        self.list_widget.addItem(item1)                                                                                                                                                                                                       
        self.list_widget.addItem(item2)                                                                                                                                                                                                       
        self.list_widget.addItem(item3)                                                                                                                                                                                                       
                                                                                                                                                                                                                                              
        # Mise en place de la fenêtre                                                                                                                                                                                                         
        layout = QVBoxLayout()                                                                                                                                                                                                                
        layout.addWidget(self.list_widget)                                                                                                                                                                                                    
        self.setLayout(layout)                                                                                                                                                                                                                
                                                                                                                                                                                                                                              
app = QApplication(sys.argv)                                                                                                                                                                                                                  
window = MainWindow()                                                                                                                                                                                                                         
window.show()                                                                                                                                                                                                                                 
sys.exit(app.exec())                                                                                                                                                                                                                          

